// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function newComp(comp: Competition) {
    return invoke<null>("new_comp", { comp })
}

export function getComps() {
    return invoke<Competition[]>("get_comps")
}

export function pitScout(name: string, teamNumber: number, value: any) {
    return invoke<null>("pit_scout", { name,teamNumber,value })
}

export function matchScout(teamType: TeamType, teamNumber: number, matchNumber: number, data: any) {
    return invoke<null>("match_scout", { teamType,teamNumber,matchNumber,data })
}

export function uploadSchema(schema: Field[], schemaType: SchemaType) {
    return invoke<null>("upload_schema", { schema,schemaType })
}

export function getSchema(schemaType: SchemaType) {
    return invoke<Field[] | null>("get_schema", { schemaType })
}

export type Number = { label: string; name: string }
export type Competition = { name: string; tba_key: string; match_schema: Field[]; pit_schema: Field[] }
export type Field = { Checkbox: Checkbox } | { Number: Number } | { Choice: Choice } | { Text: Text }
export type Text = { label: string; name: string }
export type SchemaType = "PIT" | "MATCH"
export type TeamType = "RED1" | "RED2" | "RED3" | "BLUE1" | "BLUE2" | "BLUE3"
export type Choice = { label: string; one_of: string[]; name: string }
export type Checkbox = { label: string; name: string }
