name: CI
 
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  lint:
      name: Lint and Check
      timeout-minutes: 15
      runs-on: ubuntu-latest
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2
 
        - uses: pnpm/action-setup@v2.0.1
          with:
            version: 6.32.2
 
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'pnpm'
        - name: setup rust + cargo
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
        
        - name: setup tauri deps
          run: sudo apt update && sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
 
        - name: Install dependencies
          run: pnpm install
 
        - name: Lint and check
          run: pnpm lint